#ifndef MOTOR_INIT_H
#define	MOTOR_INIT_H


// Definition des états de la machine de gestion du mode init
typedef enum
{
  MOTOR_INIT_NOP, 
          
  MOTOR_INIT_RESET_MOTOR_PARAMS1,
  MOTOR_INIT_RESET_MOTOR_PARAMS2,
  MOTOR_INIT_RESET_MOTOR_PARAMS3,
  MOTOR_INIT_RESET_MOTOR_PARAMS4,
                               
  MOTOR_INIT_WAIT_BLTDR_STOP_SCROLLING,        
  MOTOR_INIT_START, 
  MOTOR_INIT_OFF,      
          
  MOTOR_INIT_SLAVE_FILTER_ON1, 
  MOTOR_INIT_SLAVE_FILTER_ON2, 
  MOTOR_INIT_SLAVE_FILTER_ON3,  //10
  
  MOTOR_INIT_TAUTNESS_SLOPE, 
  MOTOR_INIT_TAUTNESS_TIME,
  
  MOTOR_INIT_2,
  
  MOTOR_INIT_START_ON_CELL_SLOPE,
  MOTOR_INIT_START_ON_CELL_TEMPO,
          
  MOTOR_INIT_ENRH_ACCEL_TO_FS_SLOPE,
  MOTOR_INIT_ENRH_FS,        
  MOTOR_INIT_ENRH_DECEL_TO_STOP_SLOPE,
  MOTOR_INIT_ENRH_STOP1,
  
  MOTOR_INIT_ENRH_STOP2, //20
          
  MOTOR_INIT_ENRL_ACCEL_TO_FS_SLOPE,
  MOTOR_INIT_ENRL_FS,        
  MOTOR_INIT_ENRL_DECEL_GET_PULSES,        
          
  MOTOR_INIT_ENRL_DECEL_TO_STOP_SLOPE,
  MOTOR_INIT_ENRL_STOP,
 
  MOTOR_INIT_BLINK_LED,
         
          
  MOTOR_INIT_NEW_STRUCT_WAIT_MUTEX,
  MOTOR_INIT_NEW_STRUCT,
  MOTOR_INIT_TEST_POSTER_COUNT,
  
  MOTOR_INIT_SLAVE_FILTER_OFF1, //30
  MOTOR_INIT_SLAVE_FILTER_OFF2, 
  MOTOR_INIT_SLAVE_FILTER_OFF3,           
          
  MOTOR_INIT_FIRST_PULSES1,
  MOTOR_INIT_FIRST_PULSES2,
  
  
  MOTOR_INIT_FIRST_POSTER_SLOPE_TO_FULL_SPEED,
  MOTOR_INIT_FIRST_POSTER_FULL_SPEED,//36
  MOTOR_INIT_FIRST_POSTER_SLOPE_TO_DOCKING_SPEED1,
  MOTOR_INIT_FIRST_POSTER_SLOPE_TO_DOCKING_SPEED2,  //38
  MOTOR_INIT_FIRST_POSTER_SLOPE_TO_DOCKING_SPEED3,  
  MOTOR_INIT_FIRST_POSTER_SLOPE_TO_DOCKING_SPEED4,        
  
  MOTOR_INIT_FIRST_POSTER_SET_SLAVE_DOCKING_PULSES1,
  MOTOR_INIT_FIRST_POSTER_SET_SLAVE_DOCKING_PULSES2,
          
  MOTOR_INIT_FIRST_POSTER_DOCKING_SPEED,        
  MOTOR_INIT_FIRST_POSTER_STOP_STICKER,
          
  MOTOR_INIT_ANALYSE_BRAKE,        
  MOTOR_INIT_SLOPE_BRAKE,
  MOTOR_INIT_FINAL,        
          
  MOTOR_INIT_ERROR_STOP,
  MOTOR_INIT_ERROR_STOP2,
  MOTOR_INIT_ERROR_STOP3,
          
          
          
  MOTOR_INIT_DBG_PULSE1,
  MOTOR_INIT_DBG_PULSE2,
  MOTOR_INIT_DBG_PULSE3,
  MOTOR_INIT_DBG_PULSE4,
  MOTOR_INIT_DBG_PULSE5,
  MOTOR_INIT_DBG_PULSE6,
  MOTOR_INIT_DBG_PULSE7,
  MOTOR_INIT_DBG_PULSE8,        
          
}enum_motor_INIT_sm;

// Contient le nombre d'affiches detectees
extern u8 motor_init_poster_count;

// Contient l'état en cours de la ME
extern u8 motor_init_state;


extern volatile u8 motor_init_count;

void motor_init_init_with_clear_params(void);
void motor_init_init(void);
void motor_init_sm(void);


#endif	/* MOTOR_INIT_H */

